name: Deploy to AKS

on:
  push:
    branches:
      - main  # Triggers on push to the 'main' branch
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up kubectl in GitHub Actions
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 3: Log in to Azure (use your Azure credentials in GitHub Secrets)
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} \
                   -p ${{ secrets.ARM_CLIENT_SECRET }} \
                   --tenant ${{ secrets.ARM_TENANT_ID }}
        
      # Step 4: Get AKS credentials (to access the Kubernetes cluster)
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group AKS_RG\
                                 --name MyAKSCluster

      # Step 5: Apply the Kubernetes manifests
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/service.yaml
