name: Deploy Prometheus to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allows manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 3: Log in to Azure (if you are using AKS)
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} \
                   -p ${{ secrets.ARM_CLIENT_SECRET }} \
                   --tenant ${{ secrets.ARM_TENANT_ID }}

      # Step 4: Get AKS credentials (or use your Kubernetes credentials)
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group AKS_RG \
                                 --name MyAKSCluster

      # Step 5: Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v1

      # Step 6: Add Prometheus Helm repository (prometheus-community)
      - name: Add Prometheus Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      # Step 7: Deploy Prometheus using Helm
      - name: Install Prometheus
        run: |
          helm install prometheus prometheus-community/prometheus \
            --namespace monitoring --create-namespace \
            --set alertmanager.persistentVolume.storageClass="default" \
            --set server.persistentVolume.storageClass="default"
      
      # (Optional) Step 8: Verify deployment
      - name: Verify Prometheus Deployment
        run: |
          kubectl get pods -n monitoring
